@baseUrl = https://global-keycloak.azurewebsites.net/auth/realms/master/protocol/openid-connect

###################################################################################
#### openid configuration
GET https://global-keycloak.azurewebsites.net/auth/realms/master/.well-known/openid-configuration HTTP/1.1
Content-Type: application/json

###################################################################################
### sign in
# @name sign_in
POST {{baseUrl}}/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password
&client_id=aspnetcore-keycloak
&client_secret=1beb5df9-01dd-46c3-84a8-b65eca50ad57
&resource=aspnetcore-keycloak
&username=guest
&password=guest
&scope=openid

@access_token = {{sign_in.response.body.$.access_token}}
@refresh_token = {{sign_in.response.body.$.refresh_token}}

###################################################################################
### get user info
GET {{baseUrl}}/userinfo HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

###################################################################################
### refresh token https://identitymodel.readthedocs.io/en/latest/client/token.html#requesting-a-token-using-the-refresh-token-grant-type
POST {{baseUrl}}/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token
&client_id=aspnetcore-keycloak
&client_secret=1beb5df9-01dd-46c3-84a8-b65eca50ad57
&resource=aspnetcore-keycloak
&refresh_token={{refresh_token}}